### ISSUE TITLE
HelloController

### ISSUE THREAD

**Issue by efik** [ucze/DuckAssistant#5]
# HelloController.

## Czy HelloController nie powinien witac uzytkownika i wyswietlac liste akcji ?

 W szablonie tylko umiescic linki do odpowiednich tras? 
### Uzytkownicy
- [x] Wyswietl uzytkownikow  
- [x] Dodaj uzytkownikow
- [x] Usun uzytkownikow
- [x] Edytuj uzytkownikow

### Kategorie
- [x] Wyswietl kategorie
- [x] Dodaj kategorie
- [x] Usun kategorie
- [x] Edytuj kategorie

### Zadania
- [x] Wyswietl zadania
- [x] Dodaj zadania
- [x] Usun zadania
- [x] Edytuj zadania

Niz to co jest obecnie? :octocat:

TODO: 
 - [ ] Dodać linki do tras w DefaultController :+1:

**Comment by efik** [comment]
@jzawadzki, Dobrze rozumiem?
Pozdrawiam.

**Comment by jzawadzki** [comment]
@efik ,
najlepiej to zrobić jakiś 'nagłówek' z menu ;)
JZ

**Comment by efik** [comment]
@jzawadzki, dokładnie :)
